# -*- coding: utf-8 -*-
"""
Created on Mon Jul 29 09:55:04 2013

@author: Tommy Löfstedt
@email: tommy.loefstedt@cea.fr
"""

__all__ = ['load']

import numpy as np
import structured.utils as utils
import structured.algorithms as algorithms


def load(l, density, snr, M, e):
    """Returns data generated such that we know the exact solution.

    The data generated by this function is fit to Ridge regression, i.e.:

        f(b) = (1 / 2).|Xb - y|² + (l / 2).|b|²,

    where |.|² is the squared L2 norm.

    Parameters
    ----------
    l : The L2 regularisation parameter.

    density : The density of the returned regression vector (fraction of
            non-zero elements). Must be in (0, 1].

    snr : Signal to noise ratio between model and residual.

    M : The matrix to use when building data. This matrix carries the desired
            distribution of the generated data. The generated data will be a
            scaled version of this matrix.

    e : The error vector e = Xb - y. This vector carries the desired
            distribution of the residual.

    Returns
    -------
    X : The generated X matrix.

    y : The generated y vector.

    beta : The generated regression vector.
    """
    seed = np.random.randint(2147483648)

    low = 0.0
    high = 1.0
    for i in xrange(30):
        np.random.seed(seed)
        X, y, beta = _generate(l, density, high, M, e)
        val = np.sqrt(np.sum(np.dot(X, beta) ** 2.0) / np.sum(e ** 2.0))
        if val > snr:
            break
        else:
            low = high
            high = high * 2.0

    def f(x):
        np.random.seed(seed)
        X, y, beta = _generate(l, density, x, M, e)
        return np.sqrt(np.sum(np.dot(X, beta) ** 2.0) / np.sum(e ** 2.0)) - snr

    bm = algorithms.BisectionMethod(max_iter=20)
    bm.run(utils.AnonymousClass(f=f), low, high)

    np.random.seed(seed)
    X, y, beta = _generate(l, density, bm.x, M, e)
    print "snr = %.5f = %.5f = |X.b| / |e| = %.5f / %.5f" \
            % (snr, np.linalg.norm(np.dot(X, beta) / np.linalg.norm(e)),
               np.linalg.norm(np.dot(X, beta)), np.linalg.norm(e))

    return X, y, beta
#    return _generate(l, density, snr, M, e)


def _generate(l, density, snr, M, e):

    l = float(l)
    density = float(density)
    snr = float(snr)
    p = M.shape[1]
    ps = int(round(p * density))

    beta = np.zeros((p, 1))
    for i in xrange(p):
        if i >= ps:
            beta[i, 0] = 0.0
        else:
            beta[i, 0] = U(0, 1) * snr / np.sqrt(ps)
#    beta = np.flipud(np.sort(beta, axis=0))

    X = np.zeros(M.shape)
    for i in xrange(p):
        Mte = np.dot(M[:, i].T, e)
#        if abs(Mte) < utils.TOLERANCE:  # Avoid to make alpha very large
#            Mte = 1.0

#        if i < ps:
        alpha = (-l * beta[i, 0]) / Mte
#        else:
#            alpha = Mte

        X[:, i] = alpha * M[:, i]

    y = np.dot(X, beta) - e

    return X, y, beta


def U(a, b):
    t = max(a, b)
    a = float(min(a, b))
    b = float(t)
    return (np.random.rand() * (b - a)) + a


def sign(x):
    if x > 0:
        return 1.0
    elif x < 0:
        return -1.0
    else:
        return 0.0